apiVersion: database.arangodb.com/v1alpha
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
spec:
  image: arangodb/arangodb:3.5.2
  environment: Production
  mode: Single
  tls:
    caSecretName: None
