apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- database-deployment.yaml
secretGenerator:
- envs:
  - arangodb.env
  name: arango-secrets
  namespace: api
- envs:
  - arangoroot.env
  name: arango-root
  namespace: api
- envs:
  - kiali.env
  name: kiali
  type: Opaque
  namespace: istio-system
generatorOptions:
  disableNameSuffixHash: true
