apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: propertygraph
build:
  artifacts:
  - image: gcr.io/propertygraph/frontend
    context: frontend
    sync:
      infer:
      - '**/*.js'
      - '**/*.css'
  - image: gcr.io/propertygraph/api
    context: api
    sync:
      infer:
      - '**/*.js'
      - '**/*.css'
deploy:
  kustomize:
    paths:
    - platform/overlays/minikube
portForward:
- resourceType: service
  resourceName: istio-ingressgateway
  namespace: istio-system
  port: 80
  localPort: 3000
