apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: skaffold-create-react-app
build:
  artifacts:
  - image: skaffold-create-react-app
    context: frontend
    sync:
      infer:
      - '**/*.js'
      - '**/*.css'
deploy:
  kustomize:
    path: platform/overlays/minikube
portForward:
- resourceType: deployment
  resourceName: create-react-app
  port: 3000
