apiVersion: apps/v1
kind: Deployment
metadata:
  name: propertygraph-frontend
spec:
  selector:
    matchLabels:
      app: propertygraph-frontend
  template:
    metadata:
      labels:
        app: propertygraph-frontend
    spec:
      containers:
      - name: propertygraph-frontend
        image: gcr.io/propertygraph/frontend
        ports:
        - containerPort: 3000
