apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: propertygraph-api
  name: propertygraph-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: propertygraph-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: propertygraph-api
    spec:
      containers:
      - image: gcr.io/propertygraph/api
        name: api
        env:
        - name: PROPERTYGRAPH_DB_URL
          value: http://arangodb:8529
        - name: PROPERTYGRAPH_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PROPERTYGRAPH_DB_PASSWORD
              name: arango-secrets
        resources: {}
status: {}
