kind: "ArangoDeployment"
apiVersion: database.arangodb.com/v1alpha
metadata:
  name: "arangodb"
spec:
  image: arangodb/arangodb:3.5.2
  environment: Production
  mode: Single
  tls:
    caSecretName: None
  externalAccess:
    type: None
  bootstrap:
    passwordSecretNames:
      root: arango-root
