bases:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- database-deployment.yaml
secretGenerator:
- envs:
  - .env.arangodb
  name: arango-secrets
- envs:
  - .env.arangoroot
  name: arango-root
generatorOptions:
  disableNameSuffixHash: true
