bases:
- ../../base
patchesStrategicMerge:
- traefik-ingress-controller-deployment.yaml
- azure-vote-front-ingress.yaml
- traefik-ingress-controller-service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: microsoft/azure-vote-front
  newTag: v2
resources:
- certs-claim.yaml
