apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  type: LoadBalancer
  loadBalancerIP: 35.203.115.19
  ports:
    - name: https
      port: 443
      protocol: TCP
