steps:
  - name: node:12-alpine
    id: ci
    dir: api
    entrypoint: npm
    args: ['ci']

  - name: node:12-alpine
    id: test
    dir: api
    entrypoint: npm
    args: ['test']

    # Using debug image as workaround for
    # `error building stage: open /etc/passwd: no such file or directory`
    # https://github.com/GoogleContainerTools/kaniko/issues/477
  - name: gcr.io/kaniko-project/executor:debug
    id: build
    dir: api
    args:
      - --destination=gcr.io/$PROJECT_ID/api:$BRANCH_NAME-$SHORT_SHA
      - --destination=gcr.io/$PROJECT_ID/api:latest
      - --reproducible
      - --context=/workspace/api
      - --cache=true
      - --cache-ttl=6h
