steps:
  - name: gcr.io/cloud-builders/docker
    id: start_arangodb
    entrypoint: /bin/sh
    args:
      [
        '-c',
        'docker run -d --network=cloudbuild -p=8529:8529 --name=arangodb -e ARANGO_ROOT_PASSWORD=$_DB_PASSWORD arangodb',
      ]

  - name: mikewilliamson/wait-for
    id: wait
    args: ['arangodb:8529']

  - name: node:12-alpine
    id: ci
    dir: api
    entrypoint: npm
    args: ['ci']

  - name: node:12-alpine
    id: test
    dir: api
    entrypoint: npm
    args: ['test']
    env:
      - PROPERTYGRAPH_DB_URL=$_PROPERTYGRAPH_DB_URL
      - PROPERTYGRAPH_DB_PASSWORD=$_DB_PASSWORD

  - name: gcr.io/kaniko-project/executor
    id: build
    dir: api
    args:
      - --destination=gcr.io/$PROJECT_ID/api:$BRANCH_NAME-$SHORT_SHA
      - --destination=gcr.io/$PROJECT_ID/api:latest
      - --reproducible
      - --context=/workspace/api
      - --cache=true
      - --cache-ttl=6h
