steps:
  - name: gcr.io/cloud-builders/docker
    id: start_arangodb
    args: [
        "run", "-d", "--network=cloudbuild", "-e ARANGO_ROOT_PASSWORD=$_DB_PASSWORD", "--name=arangodb", "arangodb"
      ]

  - name: jwilder/dockerize:0.6.1
    args: ['dockerize', '-timeout=30s', '-wait=tcp://arangodb:8529']

  - name: node:12-alpine
    id: ci
    dir: api
    entrypoint: npm
    args: ['ci']

  - name: node:12-alpine
    id: test
    dir: api
    entrypoint: npm
    args: ['test']
    env:
      - 'PROPERTYGRAPH_TEST_DB_URL=$_TEST_DB_URL'
      - 'PROPERTYGRAPH_DB_PASSWORD=$_DB_PASSWORD'

    # Using debug image as workaround for
    # `error building stage: open /etc/passwd: no such file or directory`
    # https://github.com/GoogleContainerTools/kaniko/issues/477
  - name: gcr.io/kaniko-project/executor:debug
    id: build
    dir: api
    args:
      - --destination=gcr.io/$PROJECT_ID/api:$BRANCH_NAME-$SHORT_SHA
      - --destination=gcr.io/$PROJECT_ID/api:latest
      - --reproducible
      - --context=/workspace/api
      - --cache=true
      - --cache-ttl=6h

  - name: gcr.io/cloud-builders/docker
    args: ['rm', '--force', 'arangodb']
