steps:
  - name: node:12-alpine
    id: ci
    dir: api
    entrypoint: npm
    args: ['ci']

  - name: node:12-alpine
    id: test
    dir: api
    entrypoint: npm
    args: ['test']

  - name: gcr.io/kaniko-project/executor:debug
    id: build
    dir: api
    args:
      - '--destination=gcr.io/$PROJECT_ID/api:$BRANCH_NAME-$SHORT_SHA'
      - '--destination=gcr.io/$PROJECT_ID/api:latest'
      - '--dockerfile=./Dockerfile'
      - '--reproducible'
      - '--cache=true'
      - '--cache-ttl=6h'
